using System;
using System.Collections.Generic;
using System.Text;
using NUnit.Framework;

namespace Mess
{
    public class Mess
    {
        [Test]
        public void SendMess(string mess)
        {
            Assert.Fail("autogenerated");
        }
    }
}