using System;
using System.Collections.Generic;
using System.Text;
using NUnit.Framework;

namespace Mesh
{
    public class Mesh
    {
        [Test]
        public void SendMess(string mess)
        {
            Assert.Fail("autogenerated");
        }
    }
}